export const products = [
  {
    slug: "nike-sport-shoes",
    title: "کفش ورزشی نایک",
    price: "€49.99",
    oldPrice: "€69.99",
    category: "کفش ورزشی",
    image: "/figma-assets/Product Card.png",
    gallery: ["/figma-assets/Product Card.png", "/products/shoe.jpg", "/products/shoe.jpg"],
    description: "کفش ورزشی سبک و راحت با طراحی مدرن، مناسب استفاده روزمره و تمرین‌های ورزشی.",
    colors: ["#111827", "#f8fafc", "#7c3aed"],
    sizes: ["40", "41", "42", "43", "44"],
  },
  {
    slug: "classic-leather-bag",
    title: "کیف چرمی کلاسیک",
    price: "€119.99",
    oldPrice: "€149.99",
    category: "کیف",
    image: "/figma-assets/Image-1.png",
    gallery: ["/figma-assets/Image-1.png", "/products/bag.jpg"],
    description: "کیف چرمی مینیمال با فضای کافی برای استفاده روزمره.",
    colors: ["#111827", "#92400e"],
    sizes: [],
  },
  {
    slug: "everyday-jacket",
    title: "کت روزمره",
    price: "€89.99",
    oldPrice: "€119.99",
    category: "ست",
    image: "/products/jacket.jpg",
    gallery: ["/products/jacket.jpg"],
    description: "کت سبک و کاربردی با فرم ساده و مناسب استایل روزانه.",
    colors: ["#111827", "#f8fafc"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    slug: "essential-t-shirt",
    title: "تیشرت Essential",
    price: "€34.99",
    oldPrice: "€44.99",
    category: "ست",
    image: "/products/shirt.jpg",
    gallery: ["/products/shirt.jpg"],
    description: "تیشرت ساده و راحت از پارچه لطیف برای استفاده روزمره.",
    colors: ["#111827", "#f8fafc", "#c4b5fd"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    slug: "sony-headphones",
    title: "هدفون سونی",
    price: "€89.99",
    oldPrice: "€109.99",
    category: "لوازم دیجیتال",
    image: "/products/headphones.jpg",
    gallery: ["/products/headphones.jpg", "/products/headphones.jpg"],
    description: "هدفون بی‌سیم با صدای شفاف، طراحی راحت و باتری مناسب استفاده روزانه.",
    colors: ["#111827", "#f8fafc"],
    sizes: [],
  },
  {
    slug: "mechanical-keyboard",
    title: "کیبورد مکانیکال",
    price: "€129.99",
    oldPrice: "€149.99",
    category: "لوازم دیجیتال",
    image: "/products/keyboard.jpg",
    gallery: ["/products/keyboard.jpg", "/products/keyboard.jpg"],
    description: "کیبورد مکانیکال دقیق و بادوام با نورپردازی جذاب برای کار و بازی.",
    colors: ["#111827", "#f8fafc"],
    sizes: [],
  },
  {
    slug: "samsung-smart-watch",
    title: "ساعت هوشمند سامسونگ",
    price: "€199.99",
    oldPrice: "€229.99",
    category: "لوازم دیجیتال",
    image: "/products/watch.jpg",
    gallery: ["/products/watch.jpg", "/products/watch.jpg"],
    description: "ساعت هوشمند شیک با قابلیت پایش فعالیت‌های روزانه و اعلان‌های تلفن همراه.",
    colors: ["#111827", "#c4b5fd"],
    sizes: [],
  },
  {
    slug: "ray-ban-sunglasses",
    title: "عینک آفتابی ری‌بن",
    price: "€129.99",
    oldPrice: "€159.99",
    category: "اکسسوری",
    image: "/products/sunglasses.jpg",
    gallery: ["/products/sunglasses.jpg"],
    description: "عینک آفتابی سبک با طراحی کلاسیک و محافظت مناسب در برابر نور خورشید.",
    colors: ["#111827", "#92400e"],
    sizes: [],
  },
];

export function getProduct(slug) {
  return products.find((product) => product.slug === slug) || products[0];
}
